[versions]
agp = "8.8.0"
imageCropper = "4.6.0"
hiltAndroid = "2.56.2"
kotlin = "2.1.21"
kotlinxSerializationJson = "1.8.1"
ksp = "2.1.21-2.0.2"
hilt = "2.56.2"
media3 = "1.8.0"
nav = "2.9.2"
glide = "4.16.0"
glideCompose = "1.0.0-beta01"
retrofit = "3.0.0"
retrofitKotlinxSerialization = "1.0.0"
room = "2.7.2"
xxpermissions = "21.2"
workRuntimeKtx = "2.10.4"
activityCompose = "1.10.1"
composeBom = "2025.09.00"
lifecycleRuntimeKtx = "2.9.2"
lifecycleViewmodelCompose = "2.9.2"
kotlinxCoroutines = "1.8.0"
appcompat = "1.6.1"
media = "1.7.0"
multidex = "2.0.1"
paletteKtx = "1.0.0"
billingclient = "7.1.0"
material = "1.11.0"
bugly = "3.3.9"
leakcanary = "2.14"
sardineAndroid = "0.9"
timber = "5.0.1"
tinypinyin = "2.0.3.RELEASE"
hiltNavigationCompose = "1.2.0"
reorderable = "2.5.1"
junit = "1.3.0"
espressoCore = "3.7.0"
uiautomator = "2.3.0"
benchmarkMacroJunit4 = "1.4.1"
baselineprofile = "1.4.1"
profileinstaller = "1.4.1"
rules = "1.7.0"
smbj = "0.13.0"
play-feature-delivery = "2.1.0"
annotation = "1.7.0"

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-test = { id = "com.android.test", version.ref = "agp" }
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }

[libraries]
# kotlin
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }

# androidx
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation"}
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
media = { group = "androidx.media", name = "media", version.ref = "media" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }
palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "paletteKtx" }

# google
billingclient = { group = "com.android.billingclient", name = "billing", version.ref = "billingclient" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
play-feature-delivery = { group = "com.google.android.play", name = "feature-delivery", version.ref = "play-feature-delivery"}
play-feature-delivery-ktx = { group = "com.google.android.play", name = "feature-delivery-ktx", version.ref = "play-feature-delivery"}

# glide
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-ksp = { group = "com.github.bumptech.glide", name = "ksp", version.ref = "glide" }
glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glideCompose" }

# retrofit
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerialization" }

# room
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

# other
image-cropper = { module = "com.vanniktech:android-image-cropper", version.ref = "imageCropper" }
bugly = { group = "com.tencent.bugly", name = "crashreport", version.ref = "bugly" }
leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
xxpermissions = { module = "com.github.getActivity:XXPermissions", version.ref = "xxpermissions" }
sardine-android = { group = "com.github.thegrizzlylabs", name = "sardine-android", version.ref = "sardineAndroid" }
smbj = { group = "com.hierynomus", name = "smbj", version.ref = "smbj" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

# compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelCompose" }
androidx-nav = { module = "androidx.navigation:navigation-compose", version.ref = "nav" }
androidx-hilt-navi-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

# test
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmarkMacroJunit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }
androidx-rules = { group = "androidx.test", name = "rules", version.ref = "rules" }
